import 'package:flutter/widgets.dart';
import 'package:provider/provider.dart';
import 'package:pranaverse/core/providers/app_settings_provider.dart';

class AppCopy {
  const AppCopy._();

  static AppLanguage languageOf(BuildContext context, {bool listen = true}) {
    return Provider.of<AppSettingsProvider>(context, listen: listen).language;
  }

  static String of(
    BuildContext context,
    String key, {
    Map<String, Object?> vars = const {},
  }) {
    return tr(languageOf(context), key, vars: vars);
  }

  static String read(
    BuildContext context,
    String key, {
    Map<String, Object?> vars = const {},
  }) {
    return tr(languageOf(context, listen: false), key, vars: vars);
  }

  static String tr(
    AppLanguage language,
    String key, {
    Map<String, Object?> vars = const {},
  }) {
    final map = _text[language] ?? const <String, String>{};
    final english = _text[AppLanguage.english] ?? const <String, String>{};
    final value = map[key] ?? english[key] ?? key;
    return _replaceVars(value, vars);
  }

  static String voice(
    AppLanguage language,
    String text, {
    Map<String, Object?> vars = const {},
  }) {
    if (text.isEmpty) return text;

    final translated = tr(language, text, vars: vars);
    if (translated != text || language == AppLanguage.english) {
      return translated;
    }

    final boxMatch = RegExp(r'^Box (\d+) complete$').firstMatch(text);
    if (boxMatch != null) {
      return tr(
        language,
        'voiceBoxComplete',
        vars: {'count': boxMatch.group(1)},
      );
    }

    final cycleMatch = RegExp(r'^Cycle (\d+) complete$').firstMatch(text);
    if (cycleMatch != null) {
      return tr(
        language,
        'voiceCycleComplete',
        vars: {'count': cycleMatch.group(1)},
      );
    }

    if (text.endsWith(' selected')) {
      final name = text.substring(0, text.length - ' selected'.length);
      return tr(
        language,
        'themeSelectedVoice',
        vars: {'theme': tr(language, name)},
      );
    }

    return text;
  }

  static List<String> list(AppLanguage language, String key) {
    final map = _lists[language] ?? _lists[AppLanguage.english]!;
    return map[key] ?? _lists[AppLanguage.english]![key] ?? const <String>[];
  }

  static String poseInstruction(AppLanguage language, String poseName) {
    final map =
        _poseInstructions[language] ?? _poseInstructions[AppLanguage.english]!;
    return map[poseName] ??
        _poseInstructions[AppLanguage.english]![poseName] ??
        poseName;
  }

  static String languageName(
      AppLanguage currentLanguage, AppLanguage language) {
    switch (language) {
      case AppLanguage.english:
        return tr(currentLanguage, 'English');
      case AppLanguage.hindi:
        return tr(currentLanguage, 'Hindi');
      case AppLanguage.bengali:
        return tr(currentLanguage, 'Bengali');
    }
  }

  static String voicePersonalityName(
    AppLanguage language,
    Object personality,
  ) {
    final name = personality.toString().split('.').last;
    switch (name) {
      case 'buddha':
        return tr(language, 'Buddha');
      case 'zeno':
        return tr(language, 'Zeno');
      case 'monk':
        return tr(language, 'Monk');
      default:
        return tr(language, name);
    }
  }

  static String greeting(AppLanguage language) {
    final hour = DateTime.now().hour;
    if (hour < 12) return tr(language, 'Good morning');
    if (hour < 17) return tr(language, 'Good afternoon');
    return tr(language, 'Good evening');
  }

  static String _replaceVars(String value, Map<String, Object?> vars) {
    var result = value;
    vars.forEach((key, val) {
      result = result.replaceAll('{$key}', '${val ?? ''}');
    });
    return result;
  }

  static const Map<AppLanguage, Map<String, String>> _text = {
    AppLanguage.english: {
      'appTitle': 'Mindfulness Garden',
      'Mindfulness Garden': 'Mindfulness Garden',
      'Home': 'Home',
      'Garden': 'Garden',
      'Progress': 'Progress',
      'Profile': 'Profile',
      'Settings': 'Settings',
      'Sessions': 'Sessions',
      'Minutes': 'Minutes',
      'Garden Lv': 'Garden Lv',
      'Mood': 'Mood',
      'Health': 'Health',
      'Premium': 'Premium',
      'CommunityTab': 'Community',
      'Dashboard': 'Dashboard',
      'Analytics': 'Analytics',
      'Language': 'Language',
      'General': 'General',
      'Data': 'Data',
      'About': 'About',
      'Account': 'Account',
      'App': 'App',
      'English': 'English',
      'Hindi': 'Hindi',
      'Bengali': 'Bengali',
      'Good morning': 'Good morning',
      'Good afternoon': 'Good afternoon',
      'Good evening': 'Good evening',
      'Start': 'Start',
      'Pause': 'Pause',
      'Resume': 'Resume',
      'Mindful Gardener': 'Mindful Gardener',
      'Coming Soon': 'Coming Soon',
      'OK': 'OK',
      'routeComingSoon': '{route} is coming soon!',
      'Begin Today': 'Begin Today',
      'Start a 2-min Zeno breathing session':
          'Start a 2-min Zeno breathing session',
      'BREATHE': 'BREATHE',
      'MEDITATE': 'MEDITATE',
      'YOGA': 'YOGA',
      'WELLNESS': 'WELLNESS',
      'COMMUNITY': 'COMMUNITY',
      'Zeno Breathing': 'Zeno Breathing',
      'Box Breathing': 'Box Breathing',
      '4-7-8 Breathing': '4-7-8 Breathing',
      'Breath Awareness': 'Breath Awareness',
      'Alternate Nostril': 'Alternate Nostril',
      'Diaphragmatic': 'Diaphragmatic',
      'Deep Diaphragmatic': 'Deep Diaphragmatic',
      'Guided Meditation': 'Guided Meditation',
      'Audio Meditation': 'Audio Meditation',
      'Meditation Scenes': 'Meditation Scenes',
      'AI Coach': 'AI Coach',
      'Binaural Beats': 'Binaural Beats',
      'Sound Therapy': 'Sound Therapy',
      'Yoga with Zeno': 'Yoga with Zeno',
      'Meditation Music': 'Meditation Music',
      'My Garden': 'My Garden',
      'Mood Tracker': 'Mood Tracker',
      'Sleep Tracker': 'Sleep Tracker',
      'Heart Rate': 'Heart Rate',
      'Daily Challenges': 'Daily Challenges',
      'Friends': 'Friends',
      'Achievements': 'Achievements',
      'Stress relief': 'Stress relief',
      'Focus & calm': 'Focus & calm',
      'Sleep & anxiety': 'Sleep & anxiety',
      'Mindfulness': 'Mindfulness',
      'Balance': 'Balance',
      'Deep relax': 'Deep relax',
      'Expert-led': 'Expert-led',
      'Immersive sound': 'Immersive sound',
      '5 environments': '5 environments',
      'Personalised': 'Personalised',
      'Brainwaves': 'Brainwaves',
      'Frequencies': 'Frequencies',
      '2.5D immersive': '2.5D immersive',
      'Curated tracks': 'Curated tracks',
      'Grow & harvest': 'Grow & harvest',
      'Daily logging': 'Daily logging',
      'Sleep analysis': 'Sleep analysis',
      'Biometrics': 'Biometrics',
      'Your journey': 'Your journey',
      'Daily missions': 'Daily missions',
      'Meditate together': 'Meditate together',
      'Badges & rewards': 'Badges & rewards',
      'Overview': 'Overview',
      'Your trends': 'Your trends',
      'Personalize your garden': 'Personalize your garden',
      'Local garden profile': 'Local garden profile',
      'Notifications': 'Notifications',
      'Daily reminders and garden streaks':
          'Daily reminders and garden streaks',
      'Daily reminders & streaks': 'Daily reminders & streaks',
      'Open Teacher Studio': 'Open Teacher Studio',
      'Personality': 'Personality',
      'Buddha': 'Buddha',
      'Zeno': 'Zeno',
      'Monk': 'Monk',
      'Buddha voice selected': 'Buddha voice selected',
      'Zeno voice selected': 'Zeno voice selected',
      'Monk voice selected': 'Monk voice selected',
      'Garden Serenity': 'Garden Serenity',
      'Sky Calm': 'Sky Calm',
      'Sunrise Glow': 'Sunrise Glow',
      'Rose Harmony': 'Rose Harmony',
      'Lavender Dream': 'Lavender Dream',
      'Midnight Zen': 'Midnight Zen',
      'themeSelectedVoice': '{theme} selected',
      'Your calm garden profile': 'Your calm garden profile',
      'You are logged in': 'You are logged in',
      'Premium Features': 'Premium Features',
      'Sign in to unlock premium features':
          'Sign in to unlock premium features',
      'Advanced Meditations': 'Advanced Meditations',
      'Access to 500+ guided sessions': 'Access to 500+ guided sessions',
      'Premium Audio': 'Premium Audio',
      'High-quality binaural beats and music':
          'High-quality binaural beats and music',
      'Detailed Analytics': 'Detailed Analytics',
      'Track your mindfulness journey': 'Track your mindfulness journey',
      'Exclusive Plants': 'Exclusive Plants',
      'Unlock rare garden plants': 'Unlock rare garden plants',
      'Community Features': 'Community Features',
      'Earn badges and compete on leaderboards':
          'Earn badges and compete on leaderboards',
      'Join groups and share experiences': 'Join groups and share experiences',
      'Choose Avatar': 'Choose Avatar',
      'Health Matrix': 'Health Matrix',
      'AGE GROUP': 'AGE GROUP',
      'PRIMARY GOAL': 'PRIMARY GOAL',
      'HEALTH CONDITIONS': 'HEALTH CONDITIONS',
      'Under 18': 'Under 18',
      '18–25': '18–25',
      '26–35': '26–35',
      '36–45': '36–45',
      '46–55': '46–55',
      '55+': '55+',
      'Reduce stress & anxiety': 'Reduce stress & anxiety',
      'Sleep better': 'Sleep better',
      'Improve focus & productivity': 'Improve focus & productivity',
      'Manage emotions': 'Manage emotions',
      'Build daily mindfulness habit': 'Build daily mindfulness habit',
      'Recover from burnout': 'Recover from burnout',
      'General wellbeing': 'General wellbeing',
      'Depression': 'Depression',
      'Insomnia': 'Insomnia',
      'Chronic Stress': 'Chronic Stress',
      'High Blood Pressure': 'High Blood Pressure',
      'Chronic Pain': 'Chronic Pain',
      'ADHD': 'ADHD',
      'PTSD': 'PTSD',
      'Burnout': 'Burnout',
      'Grief': 'Grief',
      'Panic Attacks': 'Panic Attacks',
      'None of the above': 'None of the above',
      'moreCount': '+{count} more',
      'No conditions set. Zeno uses time-based recommendations.':
          'No conditions set. Zeno uses time-based recommendations.',
      'Zeno is calibrated for: {conditions}':
          'Zeno is calibrated for: {conditions}',
      'Zeno uses this to personalise every exercise recommendation.':
          'Zeno uses this to personalise every exercise recommendation.',
      'PREFERENCES': 'PREFERENCES',
      'Sounds & Music': 'Sounds & Music',
      'Ambient sounds during sessions': 'Ambient sounds during sessions',
      'DAILY REMINDER TIME': 'DAILY REMINDER TIME',
      'GUIDED VOICE LANGUAGE': 'GUIDED VOICE LANGUAGE',
      'VOICE PERSONALITY': 'VOICE PERSONALITY',
      'Export My Data': 'Export My Data',
      'Download all your sessions & moods':
          'Download all your sessions & moods',
      'Reset Progress': 'Reset Progress',
      'Clear all sessions and start fresh':
          'Clear all sessions and start fresh',
      'Delete Account': 'Delete Account',
      'Permanently remove all data': 'Permanently remove all data',
      'Version': 'Version',
      'Package': 'Package',
      'AI Coach Feature': 'AI Coach',
      'Sign Out': 'Sign Out',
      'Disconnect from your account': 'Disconnect from your account',
      'Signed out': 'Signed out',
      'Export coming soon': 'Export coming soon',
      'Reset Progress?': 'Reset Progress?',
      'This will clear all sessions, moods and streaks. Cannot be undone.':
          'This will clear all sessions, moods and streaks. Cannot be undone.',
      'Reset coming soon': 'Reset coming soon',
      'Delete Account?': 'Delete Account?',
      'All data will be permanently deleted. This cannot be undone.':
          'All data will be permanently deleted. This cannot be undone.',
      'Delete coming soon': 'Delete coming soon',
      'Cancel': 'Cancel',
      'Reset': 'Reset',
      'Delete': 'Delete',
      'Breathing Exercises': 'Breathing Exercises',
      'Master your breath to master your mind':
          'Master your breath to master your mind',
      'Breathing Guide': 'Breathing Guide',
      'Follow the animated circle. Inhale as it expands, exhale as it contracts.':
          'Follow the animated circle. Inhale as it expands, exhale as it contracts.',
      'All': 'All',
      'Quick': 'Quick',
      'Stress': 'Stress',
      'Focus': 'Focus',
      'Sleep': 'Sleep',
      'Release stress & tension': 'Release stress & tension',
      'For anxiety & sleep': 'For anxiety & sleep',
      'Improve focus & calm': 'Improve focus & calm',
      'Mindfulness meditation': 'Mindfulness meditation',
      'Balance & energy flow': 'Balance & energy flow',
      'Full relaxation': 'Full relaxation',
      '5 min': '5 min',
      '4 min': '4 min',
      '7 min': '7 min',
      '8 min': '8 min',
      '10 min': '10 min',
      '2.5D immersive experience': '2.5D immersive experience',
      'Choose your environment': 'Choose your environment',
      'ENVIRONMENT': 'ENVIRONMENT',
      'TIME OF DAY': 'TIME OF DAY',
      'TEACHER': 'TEACHER',
      'SEQUENCE PREVIEW': 'SEQUENCE PREVIEW',
      'Begin Yoga Session': 'Begin Yoga Session',
      'Benefits': 'Benefits',
      'Next Pose': 'Next Pose',
      'Pose {current} of {total}': 'Pose {current} of {total}',
      '{seconds}s remaining': '{seconds}s remaining',
      'Forest': 'Forest',
      'Ocean': 'Ocean',
      'Mountain': 'Mountain',
      'Cosmic': 'Cosmic',
      'Desert': 'Desert',
      'Zen Temple': 'Zen Temple',
      'Dawn': 'Dawn',
      'Morning': 'Morning',
      'Afternoon': 'Afternoon',
      'Dusk': 'Dusk',
      'Night': 'Night',
      'Mountain Pose': 'Mountain Pose',
      'Warrior I': 'Warrior I',
      'Tree Pose': 'Tree Pose',
      'Warrior I (other)': 'Warrior I (other)',
      "Child's Pose": "Child's Pose",
      'Downward Dog': 'Downward Dog',
      'Lotus Meditation': 'Lotus Meditation',
      'Stand tall, breathe deep': 'Stand tall, breathe deep',
      'Ground your feet, reach up': 'Ground your feet, reach up',
      'Find your balance': 'Find your balance',
      'Switch sides, stay strong': 'Switch sides, stay strong',
      'Lengthen your spine': 'Lengthen your spine',
      'Rest and restore': 'Rest and restore',
      'Breathe and be still': 'Breathe and be still',
      'Today, {name}': 'Today, {name}',
      '{count} day streak': '{count} day streak',
      'Start Today\'s Plan': 'Start Today\'s Plan',
      'Open Garden': 'Open Garden',
      'Today\'s Plan': 'Today\'s Plan',
      'Your personalized yoga and meditation schedule':
          'Your personalized yoga and meditation schedule',
      'AI Companion Insight': 'AI Companion Insight',
      'Personalized guidance from Zeno': 'Personalized guidance from Zeno',
      'Living Garden': 'Living Garden',
      'Grow your mindfulness garden': 'Grow your mindfulness garden',
      'Breathing Studio': 'Breathing Studio',
      'Guided breathing exercises': 'Guided breathing exercises',
      'Master your breath with guided exercises':
          'Master your breath with guided exercises',
      'Open': 'Open',
      'Momentum Circle': 'Momentum Circle',
      'Track your progress streak': 'Track your progress streak',
      'Reward Vault': 'Reward Vault',
      'Unlock achievements and rewards': 'Unlock achievements and rewards',
      'Quick Actions': 'Quick Actions',
      'Start your session instantly': 'Start your session instantly',
      'Unlogged': 'Unlogged',
      'Mood: {mood}': 'Mood: {mood}',
      'Energy {rating}/5': 'Energy {rating}/5',
      'Rate today': 'Rate today',
      'AI Companion Active': 'AI Companion Active',
      'Level {level}': 'Level {level}',
      'Lv {level}': 'Lv {level}',
      '{count} charms': '{count} charms',
      'Choose Your Guide': 'Choose Your Guide',
      'Select Your Meditation Teacher': 'Select Your Meditation Teacher',
      'Each teacher offers unique guidance for your mindfulness journey. Choose the one that resonates with you.':
          'Each teacher offers unique guidance for your mindfulness journey. Choose the one that resonates with you.',
      'SELECTED': 'SELECTED',
      'Wisdom': 'Wisdom',
      'Calm': 'Calm',
      'Customize {name}': 'Customize {name}',
      'Voice Tone': 'Voice Tone',
      'Adjust the teacher\'s voice characteristics':
          'Adjust the teacher\'s voice characteristics',
      'Hear this guide': 'Hear this guide',
      'Guidance Style': 'Guidance Style',
      'Choose how detailed the guidance should be':
          'Choose how detailed the guidance should be',
      'Appearance': 'Appearance',
      'Customize visual elements': 'Customize visual elements',
      'Ancient wisdom and peaceful guidance for deep meditation and inner peace.':
          'Ancient wisdom and peaceful guidance for deep meditation and inner peace.',
      'Modern coaching approach with motivational energy and practical mindfulness techniques.':
          'Modern coaching approach with motivational energy and practical mindfulness techniques.',
      'Traditional discipline and structured practice for building lasting meditation habits.':
          'Traditional discipline and structured practice for building lasting meditation habits.',
      'Welcome. Let us find calm through breath and stillness.':
          'Welcome. Let us find calm through breath and stillness.',
      'Hi, I am Zeno. Let us move, breathe, and grow stronger together.':
          'Hi, I am Zeno. Let us move, breathe, and grow stronger together.',
      'Begin with one steady breath. Focus grows through patient practice.':
          'Begin with one steady breath. Focus grows through patient practice.',
      'Sign Up': 'Sign Up',
      'Sign In': 'Sign In',
      'Welcome Back': 'Welcome Back',
      'Create Account': 'Create Account',
      'Join your mindfulness journey': 'Join your mindfulness journey',
      'Continue your practice': 'Continue your practice',
      'Display name': 'Display name',
      'Email': 'Email',
      'Password': 'Password',
      'At least 6 characters': 'At least 6 characters',
      'Forgot password?': 'Forgot password?',
      'Offline Play Available': 'Offline Play Available',
      'You can practice meditation offline. Sign in to sync progress across devices.':
          'You can practice meditation offline. Sign in to sync progress across devices.',
      'Continue Offline': 'Continue Offline',
      'Reset Password': 'Reset Password',
      'Enter your email': 'Enter your email',
      'Send': 'Send',
      'Password reset email sent': 'Password reset email sent',
      'Failed to send reset email': 'Failed to send reset email',
      'Please fill in all fields': 'Please fill in all fields',
      'Please enter a display name': 'Please enter a display name',
      'Please enter a valid email': 'Please enter a valid email',
      'Password must be at least 6 characters':
          'Password must be at least 6 characters',
      'Auth failed: {error}': 'Auth failed: {error}',
      'voiceBoxComplete': 'Box {count} complete',
      'voiceCycleComplete': 'Cycle {count} complete',
      'voiceSessionStart':
          '{greeting}. The guided {sessionType} session begins now. Follow your breath and move gently.',
      'voiceSessionComplete':
          'You have practiced for {minutes} minutes. Your session is complete. Carry this calm with you.',
      'Inhale for 4 seconds': 'Inhale for 4 seconds',
      'Hold breath for 4 seconds': 'Hold breath for 4 seconds',
      'Exhale for 4 seconds': 'Exhale for 4 seconds',
      'Hold empty for 4 seconds': 'Hold empty for 4 seconds',
      'Excellent! 4 boxes complete. You\'re focused and calm!':
          'Excellent! 4 boxes complete. You\'re focused and calm!',
      'Hold for 7 seconds': 'Hold for 7 seconds',
      'Exhale slowly for 8 seconds': 'Exhale slowly for 8 seconds',
      'Excellent! 4 cycles complete. You\'re doing great!':
          'Excellent! 4 cycles complete. You\'re doing great!',
      'Exhale slowly through your mouth': 'Exhale slowly through your mouth',
      'Breathe in deeply through your nose':
          'Breathe in deeply through your nose',
      'Place one hand on your chest and one on your belly. Breathe in deeply through your nose.':
          'Place one hand on your chest and one on your belly. Breathe in deeply through your nose.',
      'Wonderful! You have completed 20 cycles of diaphragmatic breathing.':
          'Wonderful! You have completed 20 cycles of diaphragmatic breathing.',
      'Breathe in...': 'Breathe in...',
      'Release...': 'Release...',
      'Hold empty...': 'Hold empty...',
      'Well done': 'Well done',
      'Inhale 4s -> Hold 4s -> Exhale 4s -> Hold 4s  ·  Repeat 4x':
          'Inhale 4s -> Hold 4s -> Exhale 4s -> Hold 4s  ·  Repeat 4x',
      'Inhale 4s -> Hold 7s -> Exhale 8s  ·  Repeat 4x':
          'Inhale 4s -> Hold 7s -> Exhale 8s  ·  Repeat 4x',
      'Cycle: {count}/4': 'Cycle: {count}/4',
      'Cycles: {count}': 'Cycles: {count}',
      'Preparation': 'Preparation',
      'Focusing': 'Focusing',
      'Deepening': 'Deepening',
      'Closing': 'Closing',
      'Find stillness...': 'Find stillness...',
      'Focus on your breath...': 'Focus on your breath...',
      'Deepen your awareness...': 'Deepen your awareness...',
      'Gently return...': 'Gently return...',
      'BEGIN MEDITATION': 'BEGIN MEDITATION',
      'MEDITATE AGAIN': 'MEDITATE AGAIN',
      'BACK TO MENU': 'BACK TO MENU',
      'Find a comfortable position...': 'Find a comfortable position...',
      'Close your eyes gently...': 'Close your eyes gently...',
      'Bring your attention to your breath...':
          'Bring your attention to your breath...',
      'Notice the natural rhythm of your breathing...':
          'Notice the natural rhythm of your breathing...',
      'Don\'t try to change it, just observe...':
          'Don\'t try to change it, just observe...',
      'Feel the air entering your nostrils...':
          'Feel the air entering your nostrils...',
      'Notice the temperature of the breath...':
          'Notice the temperature of the breath...',
      'Feel your chest and abdomen rise and fall...':
          'Feel your chest and abdomen rise and fall...',
      'If your mind wanders, gently bring it back...':
          'If your mind wanders, gently bring it back...',
      'Continue observing your breath...': 'Continue observing your breath...',
      'Notice the space between breaths...':
          'Notice the space between breaths...',
      'Stay with the sensation of breathing...':
          'Stay with the sensation of breathing...',
      'Observe without judgment...': 'Observe without judgment...',
      'Allow thoughts to come and go...': 'Allow thoughts to come and go...',
      'Return to the breath...': 'Return to the breath...',
      'Feel the present moment...': 'Feel the present moment...',
      'Gently bring awareness back to your body...':
          'Gently bring awareness back to your body...',
      'When you\'re ready, open your eyes...':
          'When you\'re ready, open your eyes...',
      'Notice the subtle sensations of breathing...':
          'Notice the subtle sensations of breathing...',
      'Begin to bring your awareness back...':
          'Begin to bring your awareness back...',
      'Let\'s begin our breath awareness practice...':
          'Let\'s begin our breath awareness practice...',
      'Meditation paused': 'Meditation paused',
      'Resuming meditation': 'Resuming meditation',
      'Meditation complete. Well done.': 'Meditation complete. Well done.',
      'Close right nostril\nInhale through left':
          'Close right nostril\nInhale through left',
      'Hold breath\n(both nostrils closed)':
          'Hold breath\n(both nostrils closed)',
      'Close left nostril\nExhale through right':
          'Close left nostril\nExhale through right',
      'Inhale through\nright nostril': 'Inhale through\nright nostril',
      'Hold breath': 'Hold breath',
      'Exhale through\nleft nostril': 'Exhale through\nleft nostril',
      'Close your right nostril and inhale through the left':
          'Close your right nostril and inhale through the left',
      'Hold your breath': 'Hold your breath',
      'Close your left nostril and exhale through the right':
          'Close your left nostril and exhale through the right',
      'Inhale through your right nostril': 'Inhale through your right nostril',
      'Exhale through your left nostril': 'Exhale through your left nostril',
      'Exercise Complete!': 'Exercise Complete!',
      'Excellent! You have completed 10 rounds of alternate nostril breathing.':
          'Excellent! You have completed 10 rounds of alternate nostril breathing.',
      'Great job! You\'ve completed 10 rounds of Alternate Nostril Breathing.':
          'Great job! You\'ve completed 10 rounds of Alternate Nostril Breathing.',
    },
    AppLanguage.hindi: {
      'appTitle': 'सचेतन उद्यान',
      'Mindfulness Garden': 'सचेतन उद्यान',
      'Home': 'होम',
      'Garden': 'उद्यान',
      'Progress': 'प्रगति',
      'Profile': 'प्रोफाइल',
      'Settings': 'सेटिंग',
      'Sessions': 'सत्र',
      'Minutes': 'मिनट',
      'Garden Lv': 'उद्यान स्तर',
      'Mood': 'मनःस्थिति',
      'Health': 'स्वास्थ्य',
      'Premium': 'प्रीमियम',
      'CommunityTab': 'समुदाय',
      'Dashboard': 'डैशबोर्ड',
      'Analytics': 'विश्लेषण',
      'Language': 'भाषा',
      'General': 'सामान्य',
      'Data': 'डेटा',
      'About': 'परिचय',
      'Account': 'खाता',
      'App': 'ऐप',
      'English': 'अंग्रेज़ी',
      'Hindi': 'हिंदी',
      'Bengali': 'बांग्ला',
      'Good morning': 'सुप्रभात',
      'Good afternoon': 'नमस्कार',
      'Good evening': 'शुभ संध्या',
      'Start': 'शुरू करें',
      'Pause': 'विराम',
      'Resume': 'जारी रखें',
      'Mindful Gardener': 'सचेत माली',
      'Coming Soon': 'जल्द आ रहा है',
      'OK': 'ठीक है',
      'routeComingSoon': '{route} जल्द आ रहा है!',
      'Begin Today': 'आज शुरू करें',
      'Start a 2-min Zeno breathing session':
          'जेनो के साथ 2 मिनट का श्वास सत्र शुरू करें',
      'BREATHE': 'श्वास',
      'MEDITATE': 'ध्यान',
      'YOGA': 'योग',
      'WELLNESS': 'कल्याण',
      'COMMUNITY': 'समुदाय',
      'Zeno Breathing': 'जेनो श्वास',
      'Box Breathing': 'बॉक्स श्वास',
      '4-7-8 Breathing': '4-7-8 श्वास',
      'Breath Awareness': 'श्वास जागरूकता',
      'Alternate Nostril': 'अनुलोम-विलोम',
      'Diaphragmatic': 'डायाफ्रामिक',
      'Deep Diaphragmatic': 'गहरी डायाफ्रामिक श्वास',
      'Guided Meditation': 'निर्देशित ध्यान',
      'Audio Meditation': 'ध्वनि ध्यान',
      'Meditation Scenes': 'ध्यान दृश्य',
      'AI Coach': 'कृत्रिम बुद्धि प्रशिक्षक',
      'Binaural Beats': 'द्विकर्ण तरंग',
      'Sound Therapy': 'ध्वनि उपचार',
      'Yoga with Zeno': 'जेनो के साथ योग',
      'Meditation Music': 'ध्यान संगीत',
      'My Garden': 'मेरा उद्यान',
      'Mood Tracker': 'मनःस्थिति लेखा',
      'Sleep Tracker': 'नींद लेखा',
      'Heart Rate': 'हृदय गति',
      'Daily Challenges': 'दैनिक चुनौतियां',
      'Friends': 'मित्र',
      'Achievements': 'उपलब्धियां',
      'Stress relief': 'तनाव से राहत',
      'Focus & calm': 'ध्यान और शांति',
      'Sleep & anxiety': 'नींद और चिंता',
      'Mindfulness': 'सचेतता',
      'Balance': 'संतुलन',
      'Deep relax': 'गहरा आराम',
      'Expert-led': 'विशेषज्ञ मार्गदर्शन',
      'Immersive sound': 'डूबने वाला ध्वनि अनुभव',
      '5 environments': '5 वातावरण',
      'Personalised': 'व्यक्तिगत',
      'Brainwaves': 'मस्तिष्क तरंगें',
      'Frequencies': 'आवृत्तियां',
      '2.5D immersive': '2.5D डूबने वाला अनुभव',
      'Curated tracks': 'चुने हुए संगीत',
      'Grow & harvest': 'उगाएं और फसल लें',
      'Daily logging': 'दैनिक लेखा',
      'Sleep analysis': 'नींद विश्लेषण',
      'Biometrics': 'शरीर संकेत',
      'Your journey': 'आपकी यात्रा',
      'Daily missions': 'दैनिक कार्य',
      'Meditate together': 'साथ ध्यान करें',
      'Badges & rewards': 'बैज और पुरस्कार',
      'Overview': 'सारांश',
      'Your trends': 'आपकी प्रवृत्तियां',
      'Personalize your garden': 'अपने उद्यान को अपने अनुसार बनाएं',
      'Local garden profile': 'स्थानीय उद्यान प्रोफाइल',
      'Notifications': 'सूचनाएं',
      'Daily reminders and garden streaks': 'दैनिक स्मरण और उद्यान क्रम',
      'Daily reminders & streaks': 'दैनिक स्मरण और क्रम',
      'Open Teacher Studio': 'शिक्षक स्टूडियो खोलें',
      'Personality': 'व्यक्तित्व',
      'Buddha': 'बुद्ध',
      'Zeno': 'जेनो',
      'Monk': 'भिक्षु',
      'Buddha voice selected': 'बुद्ध स्वर चुना गया',
      'Zeno voice selected': 'जेनो स्वर चुना गया',
      'Monk voice selected': 'भिक्षु स्वर चुना गया',
      'Garden Serenity': 'उद्यान शांति',
      'Sky Calm': 'आकाश शांति',
      'Sunrise Glow': 'सूर्योदय आभा',
      'Rose Harmony': 'गुलाब सामंजस्य',
      'Lavender Dream': 'लैवेंडर स्वप्न',
      'Midnight Zen': 'मध्यरात्रि ज़ेन',
      'themeSelectedVoice': '{theme} चुना गया',
      'Your calm garden profile': 'आपकी शांत उद्यान प्रोफाइल',
      'You are logged in': 'आप साइन इन हैं',
      'Premium Features': 'प्रीमियम सुविधाएं',
      'Sign in to unlock premium features':
          'प्रीमियम सुविधाएं खोलने के लिए साइन इन करें',
      'Advanced Meditations': 'उन्नत ध्यान',
      'Access to 500+ guided sessions': '500 से अधिक निर्देशित सत्रों की पहुंच',
      'Premium Audio': 'प्रीमियम ध्वनि',
      'High-quality binaural beats and music':
          'उच्च गुणवत्ता की द्विकर्ण तरंगें और संगीत',
      'Detailed Analytics': 'विस्तृत विश्लेषण',
      'Track your mindfulness journey': 'अपनी सचेतता यात्रा देखें',
      'Exclusive Plants': 'विशेष पौधे',
      'Unlock rare garden plants': 'दुर्लभ उद्यान पौधे खोलें',
      'Join groups and share experiences':
          'समूहों से जुड़ें और अनुभव साझा करें',
      'Earn badges and compete on leaderboards':
          'बैज कमाएं और क्रम-सूची में आगे बढ़ें',
      'Choose Avatar': 'अवतार चुनें',
      'Health Matrix': 'स्वास्थ्य सारणी',
      'AGE GROUP': 'आयु समूह',
      'PRIMARY GOAL': 'मुख्य लक्ष्य',
      'HEALTH CONDITIONS': 'स्वास्थ्य स्थितियां',
      'Under 18': '18 से कम',
      '18–25': '18–25',
      '26–35': '26–35',
      '36–45': '36–45',
      '46–55': '46–55',
      '55+': '55+',
      'Reduce stress & anxiety': 'तनाव और चिंता घटाना',
      'Sleep better': 'बेहतर नींद',
      'Improve focus & productivity': 'ध्यान और उत्पादकता बढ़ाना',
      'Manage emotions': 'भावनाओं को संभालना',
      'Build daily mindfulness habit': 'दैनिक सचेतता आदत बनाना',
      'Recover from burnout': 'थकावट से उबरना',
      'General wellbeing': 'सामान्य कल्याण',
      'Depression': 'अवसाद',
      'Insomnia': 'अनिद्रा',
      'Chronic Stress': 'दीर्घकालिक तनाव',
      'High Blood Pressure': 'उच्च रक्तचाप',
      'Chronic Pain': 'दीर्घकालिक दर्द',
      'ADHD': 'एडीएचडी',
      'PTSD': 'पीटीएसडी',
      'Burnout': 'थकावट',
      'Grief': 'शोक',
      'Panic Attacks': 'घबराहट के दौरे',
      'None of the above': 'इनमें से कोई नहीं',
      'moreCount': '+{count} और',
      'No conditions set. Zeno uses time-based recommendations.':
          'कोई स्थिति नहीं चुनी गई। जेनो समय के आधार पर सुझाव देता है।',
      'Zeno is calibrated for: {conditions}':
          'जेनो इन बातों के लिए अनुकूलित है: {conditions}',
      'Zeno uses this to personalise every exercise recommendation.':
          'जेनो इससे हर अभ्यास सुझाव को व्यक्तिगत बनाता है।',
      'PREFERENCES': 'पसंद',
      'Sounds & Music': 'ध्वनि और संगीत',
      'Ambient sounds during sessions': 'सत्रों के दौरान पृष्ठभूमि ध्वनि',
      'DAILY REMINDER TIME': 'दैनिक स्मरण समय',
      'GUIDED VOICE LANGUAGE': 'निर्देशित स्वर भाषा',
      'VOICE PERSONALITY': 'स्वर व्यक्तित्व',
      'Export My Data': 'मेरा डेटा निर्यात करें',
      'Download all your sessions & moods':
          'अपने सभी सत्र और मनःस्थिति डाउनलोड करें',
      'Reset Progress': 'प्रगति रीसेट करें',
      'Clear all sessions and start fresh': 'सभी सत्र मिटाकर नई शुरुआत करें',
      'Delete Account': 'खाता हटाएं',
      'Permanently remove all data': 'सारा डेटा स्थायी रूप से हटाएं',
      'Version': 'संस्करण',
      'Package': 'पैकेज',
      'Sign Out': 'साइन आउट',
      'Disconnect from your account': 'अपने खाते से अलग हों',
      'Signed out': 'साइन आउट हो गया',
      'Export coming soon': 'निर्यात जल्द आएगा',
      'Reset Progress?': 'प्रगति रीसेट करें?',
      'This will clear all sessions, moods and streaks. Cannot be undone.':
          'इससे सभी सत्र, मनःस्थिति और क्रम मिट जाएंगे। इसे वापस नहीं किया जा सकता।',
      'Reset coming soon': 'रीसेट जल्द आएगा',
      'Delete Account?': 'खाता हटाएं?',
      'All data will be permanently deleted. This cannot be undone.':
          'सारा डेटा स्थायी रूप से हट जाएगा। इसे वापस नहीं किया जा सकता।',
      'Delete coming soon': 'हटाना जल्द आएगा',
      'Cancel': 'रद्द करें',
      'Reset': 'रीसेट',
      'Delete': 'हटाएं',
      'Breathing Exercises': 'श्वास अभ्यास',
      'Master your breath to master your mind':
          'मन को साधने के लिए श्वास को साधें',
      'Breathing Guide': 'श्वास मार्गदर्शक',
      'Follow the animated circle. Inhale as it expands, exhale as it contracts.':
          'चलते हुए वृत्त का अनुसरण करें। फैलते समय श्वास लें, सिकुड़ते समय छोड़ें।',
      'All': 'सभी',
      'Quick': 'त्वरित',
      'Stress': 'तनाव',
      'Focus': 'ध्यान',
      'Sleep': 'नींद',
      'Release stress & tension': 'तनाव और खिंचाव छोड़ें',
      'For anxiety & sleep': 'चिंता और नींद के लिए',
      'Improve focus & calm': 'ध्यान और शांति बढ़ाएं',
      'Mindfulness meditation': 'सचेत ध्यान',
      'Balance & energy flow': 'संतुलन और ऊर्जा प्रवाह',
      'Full relaxation': 'पूरा आराम',
      '5 min': '5 मिनट',
      '4 min': '4 मिनट',
      '7 min': '7 मिनट',
      '8 min': '8 मिनट',
      '10 min': '10 मिनट',
      'Easy': 'आसान',
      'Medium': 'मध्यम',
      'Beginner': 'आरंभिक',
      'Gentle guided breathing for stress relief':
          'तनाव राहत के लिए कोमल निर्देशित श्वास',
      'Deep breathing pattern for relaxation': 'आराम के लिए गहरी श्वास विधि',
      'Military technique for focus and control':
          'ध्यान और नियंत्रण के लिए सैनिक विधि',
      'Mindful observation of natural breath': 'स्वाभाविक श्वास का सचेत अवलोकन',
      'Traditional technique for balancing energy':
          'ऊर्जा संतुलन की पारंपरिक विधि',
      'Deep belly breathing for complete relaxation':
          'पूर्ण आराम के लिए पेट से गहरी श्वास',
      'Calms mind': 'मन शांत करता है',
      'Reduces anxiety': 'चिंता घटाता है',
      'Improves focus': 'ध्यान बढ़ाता है',
      'Promotes sleep': 'नींद में सहायक',
      'Reduces stress': 'तनाव घटाता है',
      'Balances nervous system': 'तंत्रिका तंत्र संतुलित करता है',
      'Enhances focus': 'ध्यान मजबूत करता है',
      'Improves performance': 'प्रदर्शन सुधारता है',
      'Increases awareness': 'जागरूकता बढ़ाता है',
      'Improves mindfulness': 'सचेतता बढ़ाता है',
      'Balances hemispheres': 'मस्तिष्क के दोनों भाग संतुलित करता है',
      'Increases focus': 'ध्यान बढ़ाता है',
      'Reduces tension': 'खिंचाव घटाता है',
      'Improves oxygen flow': 'ऑक्सीजन प्रवाह सुधारता है',
      'Calms nervous system': 'तंत्रिका तंत्र शांत करता है',
      'Stress Relief': 'तनाव राहत',
      'Anxiety': 'चिंता',
      'Intermediate': 'मध्य स्तर',
      'Meditation': 'ध्यान',
      'Energy': 'ऊर्जा',
      'Traditional': 'पारंपरिक',
      'Relaxation': 'आराम',
      'Deep Breathing': 'गहरी श्वास',
      'Inhale': 'श्वास लें',
      'Hold': 'रोकें',
      'Exhale': 'श्वास छोड़ें',
      'Hold Empty': 'खाली रोकें',
      'Paused': 'रुका हुआ',
      'Complete': 'पूर्ण',
      'Ready': 'तैयार',
      'Restart': 'फिर शुरू करें',
      'BOX BREATHE AGAIN': 'बॉक्स श्वास फिर करें',
      'TRY ANOTHER EXERCISE': 'दूसरा अभ्यास करें',
      'START AGAIN': 'फिर शुरू करें',
      'BACK TO EXERCISES': 'अभ्यासों पर लौटें',
      'RESET': 'रीसेट',
      'RESTART': 'फिर शुरू करें',
      'Begin when ready...': 'तैयार होने पर शुरू करें...',
      'Breathe deep into your belly...': 'पेट में गहरी श्वास लें...',
      'Hold gently...': 'धीरे से रोकें...',
      'Release slowly...': 'धीरे से छोड़ें...',
      'Great Job!': 'बहुत अच्छा!',
      'You have completed 20 cycles of diaphragmatic breathing.':
          'आपने डायाफ्रामिक श्वास के 20 चक्र पूरे किए।',
      'Done': 'हो गया',
      '2.5D immersive experience': '2.5D डूबने वाला अनुभव',
      'Choose your environment': 'अपना वातावरण चुनें',
      'ENVIRONMENT': 'वातावरण',
      'TIME OF DAY': 'दिन का समय',
      'TEACHER': 'शिक्षक',
      'SEQUENCE PREVIEW': 'क्रम पूर्वावलोकन',
      'Begin Yoga Session': 'योग सत्र शुरू करें',
      'Benefits': 'लाभ',
      'Next Pose': 'अगला आसन',
      'Pose {current} of {total}': 'आसन {current} / {total}',
      '{seconds}s remaining': '{seconds} सेकंड शेष',
      'Forest': 'वन',
      'Ocean': 'समुद्र',
      'Mountain': 'पर्वत',
      'Cosmic': 'ब्रह्मांड',
      'Desert': 'मरुस्थल',
      'Zen Temple': 'ज़ेन मंदिर',
      'Dawn': 'भोर',
      'Morning': 'सुबह',
      'Afternoon': 'दोपहर',
      'Dusk': 'सांझ',
      'Night': 'रात',
      'Mountain Pose': 'पर्वतासन',
      'Warrior I': 'वीरभद्रासन प्रथम',
      'Tree Pose': 'वृक्षासन',
      'Warrior I (other)': 'वीरभद्रासन प्रथम दूसरी ओर',
      "Child's Pose": 'बालासन',
      'Downward Dog': 'अधोमुख श्वानासन',
      'Lotus Meditation': 'पद्म ध्यान',
      'Stand tall, breathe deep': 'सीधे खड़े हों, गहरी श्वास लें',
      'Ground your feet, reach up': 'पैर जमाएं, ऊपर उठें',
      'Find your balance': 'अपना संतुलन खोजें',
      'Switch sides, stay strong': 'दूसरी ओर जाएं, मजबूत रहें',
      'Lengthen your spine': 'रीढ़ लंबी करें',
      'Rest and restore': 'आराम करें और पुनर्स्थापित हों',
      'Breathe and be still': 'श्वास लें और स्थिर रहें',
      'Today, {name}': 'आज, {name}',
      '{count} day streak': '{count} दिन का क्रम',
      'Start Today\'s Plan': 'आज की योजना शुरू करें',
      'Open Garden': 'उद्यान खोलें',
      'Today\'s Plan': 'आज की योजना',
      'Your personalized yoga and meditation schedule':
          'आपकी व्यक्तिगत योग और ध्यान समय-सारणी',
      'AI Companion Insight': 'साथी बुद्धि का सुझाव',
      'Personalized guidance from Zeno': 'जेनो से व्यक्तिगत मार्गदर्शन',
      'Living Garden': 'जीवित उद्यान',
      'Grow your mindfulness garden': 'अपना सचेतता उद्यान बढ़ाएं',
      'Breathing Studio': 'श्वास कक्ष',
      'Guided breathing exercises': 'निर्देशित श्वास अभ्यास',
      'Master your breath with guided exercises':
          'निर्देशित अभ्यासों से श्वास साधें',
      'Open': 'खोलें',
      'Momentum Circle': 'गति चक्र',
      'Track your progress streak': 'अपना प्रगति क्रम देखें',
      'Reward Vault': 'पुरस्कार भंडार',
      'Unlock achievements and rewards': 'उपलब्धियां और पुरस्कार खोलें',
      'Quick Actions': 'त्वरित कार्य',
      'Start your session instantly': 'अपना सत्र तुरंत शुरू करें',
      'Unlogged': 'दर्ज नहीं',
      'Mood: {mood}': 'मनःस्थिति: {mood}',
      'Energy {rating}/5': 'ऊर्जा {rating}/5',
      'Rate today': 'आज अंक दें',
      'AI Companion Active': 'साथी बुद्धि सक्रिय',
      'Level {level}': 'स्तर {level}',
      'Lv {level}': 'स्तर {level}',
      '{count} charms': '{count} आकर्षण',
      'Choose Your Guide': 'अपना मार्गदर्शक चुनें',
      'Select Your Meditation Teacher': 'अपना ध्यान शिक्षक चुनें',
      'Each teacher offers unique guidance for your mindfulness journey. Choose the one that resonates with you.':
          'हर शिक्षक आपकी सचेतता यात्रा के लिए अलग मार्गदर्शन देता है। जो आपसे मेल खाए, उसे चुनें।',
      'SELECTED': 'चुना गया',
      'Wisdom': 'बुद्धि',
      'Calm': 'शांति',
      'Customize {name}': '{name} को अनुकूलित करें',
      'Voice Tone': 'स्वर लहजा',
      'Adjust the teacher\'s voice characteristics': 'शिक्षक के स्वर गुण बदलें',
      'Hear this guide': 'इस मार्गदर्शक को सुनें',
      'Guidance Style': 'मार्गदर्शन शैली',
      'Choose how detailed the guidance should be':
          'मार्गदर्शन कितना विस्तृत हो चुनें',
      'Appearance': 'रूप',
      'Customize visual elements': 'दृश्य तत्व बदलें',
      'Ancient wisdom and peaceful guidance for deep meditation and inner peace.':
          'गहरे ध्यान और आंतरिक शांति के लिए प्राचीन बुद्धि और शांत मार्गदर्शन।',
      'Modern coaching approach with motivational energy and practical mindfulness techniques.':
          'प्रेरक ऊर्जा और उपयोगी सचेतता विधियों वाला आधुनिक प्रशिक्षण।',
      'Traditional discipline and structured practice for building lasting meditation habits.':
          'स्थायी ध्यान आदतों के लिए पारंपरिक अनुशासन और व्यवस्थित अभ्यास।',
      'Welcome. Let us find calm through breath and stillness.':
          'स्वागत है। आइए श्वास और स्थिरता से शांति खोजें।',
      'Hi, I am Zeno. Let us move, breathe, and grow stronger together.':
          'नमस्ते, मैं जेनो हूं। आइए साथ चलें, श्वास लें और मजबूत बनें।',
      'Begin with one steady breath. Focus grows through patient practice.':
          'एक स्थिर श्वास से शुरू करें। धैर्यपूर्ण अभ्यास से ध्यान बढ़ता है।',
      'Sign Up': 'साइन अप',
      'Sign In': 'साइन इन',
      'Welcome Back': 'फिर स्वागत है',
      'Create Account': 'खाता बनाएं',
      'Join your mindfulness journey': 'अपनी सचेतता यात्रा शुरू करें',
      'Continue your practice': 'अपना अभ्यास जारी रखें',
      'Display name': 'दिखने वाला नाम',
      'Email': 'ईमेल',
      'Password': 'पासवर्ड',
      'At least 6 characters': 'कम से कम 6 अक्षर',
      'Forgot password?': 'पासवर्ड भूल गए?',
      'Offline Play Available': 'ऑफलाइन अभ्यास उपलब्ध',
      'You can practice meditation offline. Sign in to sync progress across devices.':
          'आप ध्यान का अभ्यास ऑफलाइन कर सकते हैं। उपकरणों में प्रगति मिलाने के लिए साइन इन करें।',
      'Continue Offline': 'ऑफलाइन जारी रखें',
      'Reset Password': 'पासवर्ड रीसेट करें',
      'Enter your email': 'अपना ईमेल दर्ज करें',
      'Send': 'भेजें',
      'Password reset email sent': 'पासवर्ड रीसेट ईमेल भेजा गया',
      'Failed to send reset email': 'रीसेट ईमेल भेजने में विफल',
      'Please fill in all fields': 'कृपया सभी फ़ील्ड भरें',
      'Please enter a display name': 'कृपया दिखने वाला नाम दर्ज करें',
      'Please enter a valid email': 'कृपया सही ईमेल दर्ज करें',
      'Password must be at least 6 characters':
          'पासवर्ड कम से कम 6 अक्षरों का होना चाहिए',
      'Auth failed: {error}': 'प्रवेश विफल: {error}',
      'voiceBoxComplete': 'बॉक्स {count} पूरा हुआ',
      'voiceCycleComplete': 'चक्र {count} पूरा हुआ',
      'voiceSessionStart':
          '{greeting}. निर्देशित {sessionType} सत्र अब शुरू होता है। अपनी श्वास का अनुसरण करें और धीरे चलें।',
      'voiceSessionComplete':
          'आपने {minutes} मिनट अभ्यास किया। आपका सत्र पूरा हुआ। यह शांति अपने साथ रखें।',
      'Inhale for 4 seconds': '4 सेकंड तक श्वास लें',
      'Hold breath for 4 seconds': '4 सेकंड तक श्वास रोकें',
      'Exhale for 4 seconds': '4 सेकंड तक श्वास छोड़ें',
      'Hold empty for 4 seconds': '4 सेकंड तक खाली रोकें',
      'Excellent! 4 boxes complete. You\'re focused and calm!':
          'बहुत अच्छा! 4 बॉक्स पूरे हुए। आप केंद्रित और शांत हैं!',
      'Hold for 7 seconds': '7 सेकंड तक रोकें',
      'Exhale slowly for 8 seconds': '8 सेकंड तक धीरे श्वास छोड़ें',
      'Excellent! 4 cycles complete. You\'re doing great!':
          'बहुत अच्छा! 4 चक्र पूरे हुए। आप अच्छा कर रहे हैं!',
      'Exhale slowly through your mouth': 'मुंह से धीरे-धीरे श्वास छोड़ें',
      'Breathe in deeply through your nose': 'नाक से गहरी श्वास लें',
      'Place one hand on your chest and one on your belly. Breathe in deeply through your nose.':
          'एक हाथ छाती पर और एक पेट पर रखें। नाक से गहरी श्वास लें।',
      'Wonderful! You have completed 20 cycles of diaphragmatic breathing.':
          'बहुत सुंदर! आपने डायाफ्रामिक श्वास के 20 चक्र पूरे किए।',
      'Breathe in...': 'श्वास लें...',
      'Release...': 'छोड़ें...',
      'Hold empty...': 'खाली रोकें...',
      'Well done': 'बहुत अच्छा',
      'Inhale 4s -> Hold 4s -> Exhale 4s -> Hold 4s  ·  Repeat 4x':
          '4 सेकंड श्वास लें -> 4 सेकंड रोकें -> 4 सेकंड छोड़ें -> 4 सेकंड खाली रोकें · 4 बार दोहराएं',
      'Inhale 4s -> Hold 7s -> Exhale 8s  ·  Repeat 4x':
          '4 सेकंड श्वास लें -> 7 सेकंड रोकें -> 8 सेकंड छोड़ें · 4 बार दोहराएं',
      'Cycle: {count}/4': 'चक्र: {count}/4',
      'Cycles: {count}': 'चक्र: {count}',
      'Preparation': 'तैयारी',
      'Focusing': 'ध्यान केंद्रित',
      'Deepening': 'गहराई',
      'Closing': 'समापन',
      'Find stillness...': 'स्थिरता खोजें...',
      'Focus on your breath...': 'अपनी श्वास पर ध्यान दें...',
      'Deepen your awareness...': 'अपनी जागरूकता गहरी करें...',
      'Gently return...': 'धीरे लौटें...',
      'BEGIN MEDITATION': 'ध्यान शुरू करें',
      'MEDITATE AGAIN': 'फिर ध्यान करें',
      'BACK TO MENU': 'मेनू पर लौटें',
      'Find a comfortable position...': 'आरामदायक स्थिति में बैठें...',
      'Close your eyes gently...': 'धीरे से आंखें बंद करें...',
      'Bring your attention to your breath...': 'अपना ध्यान श्वास पर लाएं...',
      'Notice the natural rhythm of your breathing...':
          'अपनी श्वास की स्वाभाविक लय देखें...',
      'Don\'t try to change it, just observe...':
          'इसे बदलने की कोशिश न करें, बस देखें...',
      'Feel the air entering your nostrils...':
          'नथुनों में आती हवा को महसूस करें...',
      'Notice the temperature of the breath...':
          'श्वास के तापमान को महसूस करें...',
      'Feel your chest and abdomen rise and fall...':
          'छाती और पेट का उठना-गिरना महसूस करें...',
      'If your mind wanders, gently bring it back...':
          'मन भटके तो उसे धीरे से वापस लाएं...',
      'Continue observing your breath...': 'अपनी श्वास को देखते रहें...',
      'Notice the space between breaths...': 'श्वासों के बीच की जगह देखें...',
      'Stay with the sensation of breathing...':
          'श्वास की अनुभूति के साथ रहें...',
      'Observe without judgment...': 'बिना निर्णय के देखें...',
      'Allow thoughts to come and go...': 'विचारों को आने-जाने दें...',
      'Return to the breath...': 'श्वास पर लौटें...',
      'Feel the present moment...': 'वर्तमान क्षण को महसूस करें...',
      'Gently bring awareness back to your body...':
          'धीरे से जागरूकता शरीर में वापस लाएं...',
      'When you\'re ready, open your eyes...': 'जब तैयार हों, आंखें खोलें...',
      'Notice the subtle sensations of breathing...':
          'श्वास की सूक्ष्म अनुभूतियों को देखें...',
      'Begin to bring your awareness back...':
          'अपनी जागरूकता वापस लाना शुरू करें...',
      'Let\'s begin our breath awareness practice...':
          'आइए श्वास जागरूकता अभ्यास शुरू करें...',
      'Meditation paused': 'ध्यान रुका',
      'Resuming meditation': 'ध्यान फिर शुरू हो रहा है',
      'Meditation complete. Well done.': 'ध्यान पूरा हुआ। बहुत अच्छा।',
      'Close right nostril\nInhale through left':
          'दायां नथुना बंद करें\nबाएं से श्वास लें',
      'Hold breath\n(both nostrils closed)': 'श्वास रोकें\n(दोनों नथुने बंद)',
      'Close left nostril\nExhale through right':
          'बायां नथुना बंद करें\nदाएं से श्वास छोड़ें',
      'Inhale through\nright nostril': 'दाएं नथुने से\nश्वास लें',
      'Hold breath': 'श्वास रोकें',
      'Exhale through\nleft nostril': 'बाएं नथुने से\nश्वास छोड़ें',
      'Close your right nostril and inhale through the left':
          'अपना दायां नथुना बंद करें और बाएं से श्वास लें',
      'Hold your breath': 'अपनी श्वास रोकें',
      'Close your left nostril and exhale through the right':
          'अपना बायां नथुना बंद करें और दाएं से श्वास छोड़ें',
      'Inhale through your right nostril': 'अपने दाएं नथुने से श्वास लें',
      'Exhale through your left nostril': 'अपने बाएं नथुने से श्वास छोड़ें',
      'Exercise Complete!': 'अभ्यास पूरा!',
      'Excellent! You have completed 10 rounds of alternate nostril breathing.':
          'बहुत अच्छा! आपने अनुलोम-विलोम के 10 राउंड पूरे किए।',
      'Great job! You\'ve completed 10 rounds of Alternate Nostril Breathing.':
          'बहुत अच्छा! आपने अनुलोम-विलोम श्वास के 10 राउंड पूरे किए।',
    },
    AppLanguage.bengali: {
      'appTitle': 'সচেতনতার বাগান',
      'Mindfulness Garden': 'সচেতনতার বাগান',
      'Home': 'হোম',
      'Garden': 'বাগান',
      'Progress': 'অগ্রগতি',
      'Profile': 'প্রোফাইল',
      'Settings': 'সেটিংস',
      'Sessions': 'সেশন',
      'Minutes': 'মিনিট',
      'Garden Lv': 'বাগান স্তর',
      'Mood': 'মনোভাব',
      'Health': 'স্বাস্থ্য',
      'Premium': 'প্রিমিয়াম',
      'CommunityTab': 'সম্প্রদায়',
      'Dashboard': 'ড্যাশবোর্ড',
      'Analytics': 'বিশ্লেষণ',
      'Language': 'ভাষা',
      'General': 'সাধারণ',
      'Data': 'ডেটা',
      'About': 'পরিচিতি',
      'Account': 'অ্যাকাউন্ট',
      'App': 'অ্যাপ',
      'English': 'ইংরেজি',
      'Hindi': 'হিন্দি',
      'Bengali': 'বাংলা',
      'Good morning': 'সুপ্রভাত',
      'Good afternoon': 'শুভ অপরাহ্ন',
      'Good evening': 'শুভ সন্ধ্যা',
      'Start': 'শুরু করুন',
      'Pause': 'বিরতি',
      'Resume': 'চালিয়ে যান',
      'Mindful Gardener': 'সচেতন মালী',
      'Coming Soon': 'শীঘ্রই আসছে',
      'OK': 'ঠিক আছে',
      'routeComingSoon': '{route} শীঘ্রই আসছে!',
      'Begin Today': 'আজ শুরু করুন',
      'Start a 2-min Zeno breathing session':
          'জেনোর সঙ্গে ২ মিনিটের শ্বাস সেশন শুরু করুন',
      'BREATHE': 'শ্বাস',
      'MEDITATE': 'ধ্যান',
      'YOGA': 'যোগ',
      'WELLNESS': 'সুস্থতা',
      'COMMUNITY': 'সম্প্রদায়',
      'Zeno Breathing': 'জেনো শ্বাস',
      'Box Breathing': 'বক্স শ্বাস',
      '4-7-8 Breathing': '৪-৭-৮ শ্বাস',
      'Breath Awareness': 'শ্বাস সচেতনতা',
      'Alternate Nostril': 'বিকল্প নাসিকা শ্বাস',
      'Diaphragmatic': 'ডায়াফ্রামিক',
      'Deep Diaphragmatic': 'গভীর ডায়াফ্রামিক শ্বাস',
      'Guided Meditation': 'নির্দেশিত ধ্যান',
      'Audio Meditation': 'ধ্বনি ধ্যান',
      'Meditation Scenes': 'ধ্যান দৃশ্য',
      'AI Coach': 'কৃত্রিম বুদ্ধি প্রশিক্ষক',
      'Binaural Beats': 'দ্বিকর্ণ তরঙ্গ',
      'Sound Therapy': 'ধ্বনি চিকিৎসা',
      'Yoga with Zeno': 'জেনোর সঙ্গে যোগ',
      'Meditation Music': 'ধ্যান সঙ্গীত',
      'My Garden': 'আমার বাগান',
      'Mood Tracker': 'মনোভাব নথি',
      'Sleep Tracker': 'ঘুম নথি',
      'Heart Rate': 'হৃদস্পন্দন',
      'Daily Challenges': 'দৈনিক চ্যালেঞ্জ',
      'Friends': 'বন্ধু',
      'Achievements': 'অর্জন',
      'Stress relief': 'চাপ থেকে স্বস্তি',
      'Focus & calm': 'মনোযোগ ও শান্তি',
      'Sleep & anxiety': 'ঘুম ও উদ্বেগ',
      'Mindfulness': 'সচেতনতা',
      'Balance': 'ভারসাম্য',
      'Deep relax': 'গভীর আরাম',
      'Expert-led': 'বিশেষজ্ঞ নির্দেশিত',
      'Immersive sound': 'ডুবে যাওয়া ধ্বনি',
      '5 environments': '৫টি পরিবেশ',
      'Personalised': 'ব্যক্তিগত',
      'Brainwaves': 'মস্তিষ্ক তরঙ্গ',
      'Frequencies': 'কম্পাঙ্ক',
      '2.5D immersive': '২.৫ডি ডুবে যাওয়া অভিজ্ঞতা',
      'Curated tracks': 'বাছাই করা সুর',
      'Grow & harvest': 'বাড়ান ও সংগ্রহ করুন',
      'Daily logging': 'দৈনিক নথিভুক্তি',
      'Sleep analysis': 'ঘুম বিশ্লেষণ',
      'Biometrics': 'শরীর সংকেত',
      'Your journey': 'আপনার যাত্রা',
      'Daily missions': 'দৈনিক কাজ',
      'Meditate together': 'একসঙ্গে ধ্যান করুন',
      'Badges & rewards': 'ব্যাজ ও পুরস্কার',
      'Overview': 'সারাংশ',
      'Your trends': 'আপনার প্রবণতা',
      'Personalize your garden': 'আপনার বাগান নিজের মতো সাজান',
      'Local garden profile': 'স্থানীয় বাগান প্রোফাইল',
      'Notifications': 'বিজ্ঞপ্তি',
      'Daily reminders and garden streaks': 'দৈনিক স্মরণ ও বাগান ধারাবাহিকতা',
      'Daily reminders & streaks': 'দৈনিক স্মরণ ও ধারাবাহিকতা',
      'Open Teacher Studio': 'শিক্ষক স্টুডিও খুলুন',
      'Personality': 'ব্যক্তিত্ব',
      'Buddha': 'বুদ্ধ',
      'Zeno': 'জেনো',
      'Monk': 'সন্ন্যাসী',
      'Buddha voice selected': 'বুদ্ধ কণ্ঠ নির্বাচিত',
      'Zeno voice selected': 'জেনো কণ্ঠ নির্বাচিত',
      'Monk voice selected': 'সন্ন্যাসী কণ্ঠ নির্বাচিত',
      'Garden Serenity': 'বাগানের প্রশান্তি',
      'Sky Calm': 'আকাশের শান্তি',
      'Sunrise Glow': 'সূর্যোদয়ের আভা',
      'Rose Harmony': 'গোলাপের সামঞ্জস্য',
      'Lavender Dream': 'ল্যাভেন্ডার স্বপ্ন',
      'Midnight Zen': 'মধ্যরাত্রির জেন',
      'themeSelectedVoice': '{theme} নির্বাচিত',
      'Your calm garden profile': 'আপনার শান্ত বাগান প্রোফাইল',
      'You are logged in': 'আপনি সাইন ইন আছেন',
      'Premium Features': 'প্রিমিয়াম সুবিধা',
      'Sign in to unlock premium features':
          'প্রিমিয়াম সুবিধা খুলতে সাইন ইন করুন',
      'Advanced Meditations': 'উন্নত ধ্যান',
      'Access to 500+ guided sessions': '৫০০টির বেশি নির্দেশিত সেশনে প্রবেশ',
      'Premium Audio': 'প্রিমিয়াম ধ্বনি',
      'High-quality binaural beats and music':
          'উচ্চমানের দ্বিকর্ণ তরঙ্গ ও সঙ্গীত',
      'Detailed Analytics': 'বিস্তারিত বিশ্লেষণ',
      'Track your mindfulness journey': 'আপনার সচেতনতার যাত্রা দেখুন',
      'Exclusive Plants': 'বিশেষ গাছ',
      'Unlock rare garden plants': 'দুর্লভ বাগান গাছ খুলুন',
      'Join groups and share experiences': 'দলে যোগ দিন এবং অভিজ্ঞতা ভাগ করুন',
      'Earn badges and compete on leaderboards':
          'ব্যাজ অর্জন করুন এবং তালিকায় এগিয়ে থাকুন',
      'Choose Avatar': 'অবতার বাছুন',
      'Health Matrix': 'স্বাস্থ্য তালিকা',
      'AGE GROUP': 'বয়সের দল',
      'PRIMARY GOAL': 'প্রধান লক্ষ্য',
      'HEALTH CONDITIONS': 'স্বাস্থ্য অবস্থা',
      'Under 18': '১৮ বছরের কম',
      '18–25': '১৮–২৫',
      '26–35': '২৬–৩৫',
      '36–45': '৩৬–৪৫',
      '46–55': '৪৬–৫৫',
      '55+': '৫৫+',
      'Reduce stress & anxiety': 'চাপ ও উদ্বেগ কমানো',
      'Sleep better': 'ভালো ঘুম',
      'Improve focus & productivity': 'মনোযোগ ও উৎপাদনশীলতা বাড়ানো',
      'Manage emotions': 'আবেগ সামলানো',
      'Build daily mindfulness habit': 'দৈনিক সচেতনতার অভ্যাস গড়া',
      'Recover from burnout': 'অবসাদজনিত ক্লান্তি থেকে ফেরা',
      'General wellbeing': 'সামগ্রিক সুস্থতা',
      'Depression': 'বিষণ্নতা',
      'Insomnia': 'অনিদ্রা',
      'Chronic Stress': 'দীর্ঘস্থায়ী চাপ',
      'High Blood Pressure': 'উচ্চ রক্তচাপ',
      'Chronic Pain': 'দীর্ঘস্থায়ী ব্যথা',
      'ADHD': 'এডিএইচডি',
      'PTSD': 'পিটিএসডি',
      'Burnout': 'অবসাদজনিত ক্লান্তি',
      'Grief': 'শোক',
      'Panic Attacks': 'আতঙ্কের আক্রমণ',
      'None of the above': 'উপরের কোনওটি নয়',
      'moreCount': '+{count}টি আরও',
      'No conditions set. Zeno uses time-based recommendations.':
          'কোনও অবস্থা নির্ধারিত নয়। জেনো সময়ভিত্তিক পরামর্শ ব্যবহার করে।',
      'Zeno is calibrated for: {conditions}':
          'জেনো এসবের জন্য সাজানো: {conditions}',
      'Zeno uses this to personalise every exercise recommendation.':
          'জেনো এটি ব্যবহার করে প্রতিটি ব্যায়ামের পরামর্শ ব্যক্তিগত করে।',
      'PREFERENCES': 'পছন্দ',
      'Sounds & Music': 'ধ্বনি ও সঙ্গীত',
      'Ambient sounds during sessions': 'সেশনের সময় পরিবেশ ধ্বনি',
      'DAILY REMINDER TIME': 'দৈনিক স্মরণের সময়',
      'GUIDED VOICE LANGUAGE': 'নির্দেশিত কণ্ঠের ভাষা',
      'VOICE PERSONALITY': 'কণ্ঠের ব্যক্তিত্ব',
      'Export My Data': 'আমার ডেটা রপ্তানি করুন',
      'Download all your sessions & moods':
          'আপনার সব সেশন ও মনোভাব ডাউনলোড করুন',
      'Reset Progress': 'অগ্রগতি রিসেট করুন',
      'Clear all sessions and start fresh': 'সব সেশন মুছে নতুন করে শুরু করুন',
      'Delete Account': 'অ্যাকাউন্ট মুছুন',
      'Permanently remove all data': 'সব ডেটা স্থায়ীভাবে মুছুন',
      'Version': 'সংস্করণ',
      'Package': 'প্যাকেজ',
      'Sign Out': 'সাইন আউট',
      'Disconnect from your account': 'আপনার অ্যাকাউন্ট থেকে বেরিয়ে যান',
      'Signed out': 'সাইন আউট হয়েছে',
      'Export coming soon': 'রপ্তানি শীঘ্রই আসছে',
      'Reset Progress?': 'অগ্রগতি রিসেট করবেন?',
      'This will clear all sessions, moods and streaks. Cannot be undone.':
          'এতে সব সেশন, মনোভাব ও ধারাবাহিকতা মুছে যাবে। এটি ফেরানো যাবে না।',
      'Reset coming soon': 'রিসেট শীঘ্রই আসছে',
      'Delete Account?': 'অ্যাকাউন্ট মুছবেন?',
      'All data will be permanently deleted. This cannot be undone.':
          'সব ডেটা স্থায়ীভাবে মুছে যাবে। এটি ফেরানো যাবে না।',
      'Delete coming soon': 'মুছে ফেলা শীঘ্রই আসছে',
      'Cancel': 'বাতিল',
      'Reset': 'রিসেট',
      'Delete': 'মুছুন',
      'Breathing Exercises': 'শ্বাস ব্যায়াম',
      'Master your breath to master your mind':
          'মনকে আয়ত্ত করতে শ্বাসকে আয়ত্ত করুন',
      'Breathing Guide': 'শ্বাস নির্দেশিকা',
      'Follow the animated circle. Inhale as it expands, exhale as it contracts.':
          'চলমান বৃত্ত অনুসরণ করুন। বড় হলে শ্বাস নিন, ছোট হলে শ্বাস ছাড়ুন।',
      'All': 'সব',
      'Quick': 'দ্রুত',
      'Stress': 'চাপ',
      'Focus': 'মনোযোগ',
      'Sleep': 'ঘুম',
      'Release stress & tension': 'চাপ ও টান ছেড়ে দিন',
      'For anxiety & sleep': 'উদ্বেগ ও ঘুমের জন্য',
      'Improve focus & calm': 'মনোযোগ ও শান্তি বাড়ান',
      'Mindfulness meditation': 'সচেতন ধ্যান',
      'Balance & energy flow': 'ভারসাম্য ও শক্তি প্রবাহ',
      'Full relaxation': 'সম্পূর্ণ আরাম',
      '5 min': '৫ মিনিট',
      '4 min': '৪ মিনিট',
      '7 min': '৭ মিনিট',
      '8 min': '৮ মিনিট',
      '10 min': '১০ মিনিট',
      'Easy': 'সহজ',
      'Medium': 'মাঝারি',
      'Beginner': 'শুরুর স্তর',
      'Gentle guided breathing for stress relief':
          'চাপ কমাতে কোমল নির্দেশিত শ্বাস',
      'Deep breathing pattern for relaxation': 'আরামের জন্য গভীর শ্বাস পদ্ধতি',
      'Military technique for focus and control':
          'মনোযোগ ও নিয়ন্ত্রণের জন্য শৃঙ্খলাপূর্ণ পদ্ধতি',
      'Mindful observation of natural breath':
          'স্বাভাবিক শ্বাসের সচেতন পর্যবেক্ষণ',
      'Traditional technique for balancing energy':
          'শক্তির ভারসাম্যের ঐতিহ্যবাহী পদ্ধতি',
      'Deep belly breathing for complete relaxation':
          'সম্পূর্ণ আরামের জন্য পেট থেকে গভীর শ্বাস',
      'Calms mind': 'মন শান্ত করে',
      'Reduces anxiety': 'উদ্বেগ কমায়',
      'Improves focus': 'মনোযোগ বাড়ায়',
      'Promotes sleep': 'ঘুমে সাহায্য করে',
      'Reduces stress': 'চাপ কমায়',
      'Balances nervous system': 'স্নায়ুতন্ত্র ভারসাম্য করে',
      'Enhances focus': 'মনোযোগ শক্ত করে',
      'Improves performance': 'কর্মক্ষমতা বাড়ায়',
      'Increases awareness': 'সচেতনতা বাড়ায়',
      'Improves mindfulness': 'সচেতনতা উন্নত করে',
      'Balances hemispheres': 'মস্তিষ্কের দুই পাশ ভারসাম্য করে',
      'Increases focus': 'মনোযোগ বাড়ায়',
      'Reduces tension': 'টান কমায়',
      'Improves oxygen flow': 'অক্সিজেন প্রবাহ বাড়ায়',
      'Calms nervous system': 'স্নায়ুতন্ত্র শান্ত করে',
      'Stress Relief': 'চাপ মুক্তি',
      'Anxiety': 'উদ্বেগ',
      'Intermediate': 'মধ্য স্তর',
      'Meditation': 'ধ্যান',
      'Energy': 'শক্তি',
      'Traditional': 'ঐতিহ্যবাহী',
      'Relaxation': 'আরাম',
      'Deep Breathing': 'গভীর শ্বাস',
      'Inhale': 'শ্বাস নিন',
      'Hold': 'ধরে রাখুন',
      'Exhale': 'শ্বাস ছাড়ুন',
      'Hold Empty': 'খালি ধরে রাখুন',
      'Paused': 'বিরত',
      'Complete': 'সম্পূর্ণ',
      'Ready': 'প্রস্তুত',
      'Restart': 'আবার শুরু',
      'BOX BREATHE AGAIN': 'আবার বক্স শ্বাস',
      'TRY ANOTHER EXERCISE': 'আরেকটি ব্যায়াম চেষ্টা করুন',
      'START AGAIN': 'আবার শুরু করুন',
      'BACK TO EXERCISES': 'ব্যায়ামে ফিরে যান',
      'RESET': 'রিসেট',
      'RESTART': 'আবার শুরু করুন',
      'Begin when ready...': 'প্রস্তুত হলে শুরু করুন...',
      'Breathe deep into your belly...': 'পেটে গভীর শ্বাস নিন...',
      'Hold gently...': 'নরমভাবে ধরে রাখুন...',
      'Release slowly...': 'ধীরে ছাড়ুন...',
      'Great Job!': 'খুব ভালো!',
      'You have completed 20 cycles of diaphragmatic breathing.':
          'আপনি ডায়াফ্রামিক শ্বাসের ২০টি চক্র সম্পূর্ণ করেছেন।',
      'Done': 'হয়ে গেছে',
      '2.5D immersive experience': '২.৫ডি ডুবে যাওয়া অভিজ্ঞতা',
      'Choose your environment': 'আপনার পরিবেশ বাছুন',
      'ENVIRONMENT': 'পরিবেশ',
      'TIME OF DAY': 'দিনের সময়',
      'TEACHER': 'শিক্ষক',
      'SEQUENCE PREVIEW': 'ক্রমের পূর্বরূপ',
      'Begin Yoga Session': 'যোগ সেশন শুরু করুন',
      'Benefits': 'উপকার',
      'Next Pose': 'পরের আসন',
      'Pose {current} of {total}': 'আসন {current} / {total}',
      '{seconds}s remaining': '{seconds} সেকেন্ড বাকি',
      'Forest': 'অরণ্য',
      'Ocean': 'সমুদ্র',
      'Mountain': 'পাহাড়',
      'Cosmic': 'মহাকাশ',
      'Desert': 'মরুভূমি',
      'Zen Temple': 'জেন মন্দির',
      'Dawn': 'ভোর',
      'Morning': 'সকাল',
      'Afternoon': 'দুপুর',
      'Dusk': 'গোধূলি',
      'Night': 'রাত',
      'Mountain Pose': 'পর্বতাসন',
      'Warrior I': 'বীরভদ্রাসন এক',
      'Tree Pose': 'বৃক্ষাসন',
      'Warrior I (other)': 'বীরভদ্রাসন এক অন্য দিক',
      "Child's Pose": 'শিশু আসন',
      'Downward Dog': 'অধোমুখ শ্বানাসন',
      'Lotus Meditation': 'পদ্ম ধ্যান',
      'Stand tall, breathe deep': 'সোজা দাঁড়ান, গভীর শ্বাস নিন',
      'Ground your feet, reach up': 'পা স্থির করুন, ওপরে উঠুন',
      'Find your balance': 'ভারসাম্য খুঁজুন',
      'Switch sides, stay strong': 'দিক বদলান, শক্ত থাকুন',
      'Lengthen your spine': 'মেরুদণ্ড লম্বা করুন',
      'Rest and restore': 'বিশ্রাম নিন ও ফিরে আসুন',
      'Breathe and be still': 'শ্বাস নিন ও স্থির থাকুন',
      'Today, {name}': 'আজ, {name}',
      '{count} day streak': '{count} দিনের ধারাবাহিকতা',
      'Start Today\'s Plan': 'আজকের পরিকল্পনা শুরু করুন',
      'Open Garden': 'বাগান খুলুন',
      'Today\'s Plan': 'আজকের পরিকল্পনা',
      'Your personalized yoga and meditation schedule':
          'আপনার ব্যক্তিগত যোগ ও ধ্যানের সময়সূচি',
      'AI Companion Insight': 'সঙ্গী বুদ্ধির পরামর্শ',
      'Personalized guidance from Zeno': 'জেনোর ব্যক্তিগত নির্দেশনা',
      'Living Garden': 'জীবন্ত বাগান',
      'Grow your mindfulness garden': 'আপনার সচেতনতার বাগান বাড়ান',
      'Breathing Studio': 'শ্বাস কক্ষ',
      'Guided breathing exercises': 'নির্দেশিত শ্বাস ব্যায়াম',
      'Master your breath with guided exercises':
          'নির্দেশিত ব্যায়ামে শ্বাস আয়ত্ত করুন',
      'Open': 'খুলুন',
      'Momentum Circle': 'গতি বৃত্ত',
      'Track your progress streak': 'আপনার অগ্রগতির ধারাবাহিকতা দেখুন',
      'Reward Vault': 'পুরস্কার ভান্ডার',
      'Unlock achievements and rewards': 'অর্জন ও পুরস্কার খুলুন',
      'Quick Actions': 'দ্রুত কাজ',
      'Start your session instantly': 'আপনার সেশন সঙ্গে সঙ্গে শুরু করুন',
      'Unlogged': 'নথিভুক্ত নয়',
      'Mood: {mood}': 'মনোভাব: {mood}',
      'Energy {rating}/5': 'শক্তি {rating}/৫',
      'Rate today': 'আজ মূল্যায়ন করুন',
      'AI Companion Active': 'সঙ্গী বুদ্ধি সক্রিয়',
      'Level {level}': 'স্তর {level}',
      'Lv {level}': 'স্তর {level}',
      '{count} charms': '{count}টি আকর্ষণ',
      'Choose Your Guide': 'আপনার পথপ্রদর্শক বাছুন',
      'Select Your Meditation Teacher': 'আপনার ধ্যান শিক্ষক বাছুন',
      'Each teacher offers unique guidance for your mindfulness journey. Choose the one that resonates with you.':
          'প্রতিটি শিক্ষক আপনার সচেতনতার যাত্রায় আলাদা নির্দেশনা দেন। যিনি আপনার সঙ্গে মানায়, তাঁকে বাছুন।',
      'SELECTED': 'নির্বাচিত',
      'Wisdom': 'প্রজ্ঞা',
      'Calm': 'শান্তি',
      'Customize {name}': '{name} কাস্টমাইজ করুন',
      'Voice Tone': 'কণ্ঠের সুর',
      'Adjust the teacher\'s voice characteristics':
          'শিক্ষকের কণ্ঠের বৈশিষ্ট্য বদলান',
      'Hear this guide': 'এই পথপ্রদর্শক শুনুন',
      'Guidance Style': 'নির্দেশনার ধরন',
      'Choose how detailed the guidance should be':
          'নির্দেশনা কত বিস্তারিত হবে বাছুন',
      'Appearance': 'রূপ',
      'Customize visual elements': 'দৃশ্যমান অংশ বদলান',
      'Ancient wisdom and peaceful guidance for deep meditation and inner peace.':
          'গভীর ধ্যান ও অন্তরের শান্তির জন্য প্রাচীন প্রজ্ঞা ও শান্ত নির্দেশনা।',
      'Modern coaching approach with motivational energy and practical mindfulness techniques.':
          'প্রেরণা, শক্তি ও ব্যবহারিক সচেতনতার কৌশলসহ আধুনিক প্রশিক্ষণ।',
      'Traditional discipline and structured practice for building lasting meditation habits.':
          'দীর্ঘস্থায়ী ধ্যান অভ্যাসের জন্য ঐতিহ্যবাহী শৃঙ্খলা ও সাজানো অনুশীলন।',
      'Welcome. Let us find calm through breath and stillness.':
          'স্বাগতম। আসুন শ্বাস ও স্থিরতার মাধ্যমে শান্তি খুঁজে পাই।',
      'Hi, I am Zeno. Let us move, breathe, and grow stronger together.':
          'নমস্কার, আমি জেনো। আসুন একসঙ্গে চলি, শ্বাস নিই, আরও শক্ত হই।',
      'Begin with one steady breath. Focus grows through patient practice.':
          'একটি স্থির শ্বাস দিয়ে শুরু করুন। ধৈর্যের অনুশীলনে মনোযোগ বাড়ে।',
      'Sign Up': 'সাইন আপ',
      'Sign In': 'সাইন ইন',
      'Welcome Back': 'আবার স্বাগতম',
      'Create Account': 'অ্যাকাউন্ট তৈরি করুন',
      'Join your mindfulness journey': 'আপনার সচেতনতার যাত্রায় যোগ দিন',
      'Continue your practice': 'আপনার অনুশীলন চালিয়ে যান',
      'Display name': 'দেখানোর নাম',
      'Email': 'ইমেল',
      'Password': 'পাসওয়ার্ড',
      'At least 6 characters': 'কমপক্ষে ৬ অক্ষর',
      'Forgot password?': 'পাসওয়ার্ড ভুলে গেছেন?',
      'Offline Play Available': 'অফলাইন অনুশীলন আছে',
      'You can practice meditation offline. Sign in to sync progress across devices.':
          'আপনি অফলাইনে ধ্যান অনুশীলন করতে পারেন। বিভিন্ন যন্ত্রে অগ্রগতি মিলাতে সাইন ইন করুন।',
      'Continue Offline': 'অফলাইনে চালিয়ে যান',
      'Reset Password': 'পাসওয়ার্ড রিসেট করুন',
      'Enter your email': 'আপনার ইমেল লিখুন',
      'Send': 'পাঠান',
      'Password reset email sent': 'পাসওয়ার্ড রিসেট ইমেল পাঠানো হয়েছে',
      'Failed to send reset email': 'রিসেট ইমেল পাঠানো যায়নি',
      'Please fill in all fields': 'সব ঘর পূরণ করুন',
      'Please enter a display name': 'দেখানোর নাম লিখুন',
      'Please enter a valid email': 'সঠিক ইমেল লিখুন',
      'Password must be at least 6 characters':
          'পাসওয়ার্ড কমপক্ষে ৬ অক্ষরের হতে হবে',
      'Auth failed: {error}': 'প্রবেশ ব্যর্থ: {error}',
      'voiceBoxComplete': 'বক্স {count} সম্পূর্ণ',
      'voiceCycleComplete': 'চক্র {count} সম্পূর্ণ',
      'voiceSessionStart':
          '{greeting}। নির্দেশিত {sessionType} সেশন এখন শুরু হচ্ছে। আপনার শ্বাস অনুসরণ করুন এবং ধীরে চলুন।',
      'voiceSessionComplete':
          'আপনি {minutes} মিনিট অনুশীলন করেছেন। আপনার সেশন সম্পূর্ণ। এই শান্তি সঙ্গে রাখুন।',
      'Inhale for 4 seconds': '৪ সেকেন্ড শ্বাস নিন',
      'Hold breath for 4 seconds': '৪ সেকেন্ড শ্বাস ধরে রাখুন',
      'Exhale for 4 seconds': '৪ সেকেন্ড শ্বাস ছাড়ুন',
      'Hold empty for 4 seconds': '৪ সেকেন্ড খালি ধরে রাখুন',
      'Excellent! 4 boxes complete. You\'re focused and calm!':
          'চমৎকার! ৪টি বক্স সম্পূর্ণ। আপনি মনোযোগী ও শান্ত!',
      'Hold for 7 seconds': '৭ সেকেন্ড ধরে রাখুন',
      'Exhale slowly for 8 seconds': '৮ সেকেন্ড ধীরে শ্বাস ছাড়ুন',
      'Excellent! 4 cycles complete. You\'re doing great!':
          'চমৎকার! ৪টি চক্র সম্পূর্ণ। আপনি খুব ভালো করছেন!',
      'Exhale slowly through your mouth': 'মুখ দিয়ে ধীরে শ্বাস ছাড়ুন',
      'Breathe in deeply through your nose': 'নাক দিয়ে গভীরভাবে শ্বাস নিন',
      'Place one hand on your chest and one on your belly. Breathe in deeply through your nose.':
          'এক হাত বুকের উপর এবং এক হাত পেটের উপর রাখুন। নাক দিয়ে গভীরভাবে শ্বাস নিন।',
      'Wonderful! You have completed 20 cycles of diaphragmatic breathing.':
          'অসাধারণ! আপনি ডায়াফ্রামিক শ্বাসের ২০টি চক্র সম্পূর্ণ করেছেন।',
      'Breathe in...': 'শ্বাস নিন...',
      'Release...': 'ছেড়ে দিন...',
      'Hold empty...': 'খালি ধরে রাখুন...',
      'Well done': 'খুব ভালো',
      'Inhale 4s -> Hold 4s -> Exhale 4s -> Hold 4s  ·  Repeat 4x':
          '৪ সেকেন্ড শ্বাস নিন -> ৪ সেকেন্ড ধরে রাখুন -> ৪ সেকেন্ড ছাড়ুন -> ৪ সেকেন্ড খালি ধরে রাখুন · ৪ বার করুন',
      'Inhale 4s -> Hold 7s -> Exhale 8s  ·  Repeat 4x':
          '৪ সেকেন্ড শ্বাস নিন -> ৭ সেকেন্ড ধরে রাখুন -> ৮ সেকেন্ড ছাড়ুন · ৪ বার করুন',
      'Cycle: {count}/4': 'চক্র: {count}/৪',
      'Cycles: {count}': 'চক্র: {count}',
      'Preparation': 'প্রস্তুতি',
      'Focusing': 'মনোযোগ',
      'Deepening': 'গভীরতা',
      'Closing': 'সমাপ্তি',
      'Find stillness...': 'স্থিরতা খুঁজুন...',
      'Focus on your breath...': 'শ্বাসে মন দিন...',
      'Deepen your awareness...': 'সচেতনতা গভীর করুন...',
      'Gently return...': 'ধীরে ফিরে আসুন...',
      'BEGIN MEDITATION': 'ধ্যান শুরু করুন',
      'MEDITATE AGAIN': 'আবার ধ্যান করুন',
      'BACK TO MENU': 'মেনুতে ফিরুন',
      'Find a comfortable position...': 'আরামদায়ক অবস্থানে বসুন...',
      'Close your eyes gently...': 'নরমভাবে চোখ বন্ধ করুন...',
      'Bring your attention to your breath...': 'মনোযোগ শ্বাসে আনুন...',
      'Notice the natural rhythm of your breathing...':
          'আপনার শ্বাসের স্বাভাবিক ছন্দ লক্ষ্য করুন...',
      'Don\'t try to change it, just observe...':
          'এটি বদলানোর চেষ্টা করবেন না, শুধু লক্ষ্য করুন...',
      'Feel the air entering your nostrils...':
          'নাসারন্ধ্রে বাতাস ঢোকা অনুভব করুন...',
      'Notice the temperature of the breath...':
          'শ্বাসের তাপমাত্রা লক্ষ্য করুন...',
      'Feel your chest and abdomen rise and fall...':
          'বুক ও পেট ওঠা-নামা অনুভব করুন...',
      'If your mind wanders, gently bring it back...':
          'মন ঘুরে গেলে ধীরে ফিরিয়ে আনুন...',
      'Continue observing your breath...': 'শ্বাস লক্ষ্য করে যান...',
      'Notice the space between breaths...':
          'শ্বাসের মাঝের ফাঁক লক্ষ্য করুন...',
      'Stay with the sensation of breathing...':
          'শ্বাসের অনুভূতির সঙ্গে থাকুন...',
      'Observe without judgment...': 'বিচার না করে লক্ষ্য করুন...',
      'Allow thoughts to come and go...': 'ভাবনাগুলো আসতে ও যেতে দিন...',
      'Return to the breath...': 'শ্বাসে ফিরে আসুন...',
      'Feel the present moment...': 'বর্তমান মুহূর্ত অনুভব করুন...',
      'Gently bring awareness back to your body...':
          'ধীরে সচেতনতা শরীরে ফিরিয়ে আনুন...',
      'When you\'re ready, open your eyes...': 'প্রস্তুত হলে চোখ খুলুন...',
      'Notice the subtle sensations of breathing...':
          'শ্বাসের সূক্ষ্ম অনুভূতি লক্ষ্য করুন...',
      'Begin to bring your awareness back...':
          'সচেতনতা ফিরিয়ে আনতে শুরু করুন...',
      'Let\'s begin our breath awareness practice...':
          'আসুন শ্বাস সচেতনতার অনুশীলন শুরু করি...',
      'Meditation paused': 'ধ্যান বিরত',
      'Resuming meditation': 'ধ্যান আবার শুরু হচ্ছে',
      'Meditation complete. Well done.': 'ধ্যান সম্পূর্ণ। খুব ভালো।',
      'Close right nostril\nInhale through left':
          'ডান নাসারন্ধ্র বন্ধ করুন\nবাম দিক দিয়ে শ্বাস নিন',
      'Hold breath\n(both nostrils closed)':
          'শ্বাস ধরে রাখুন\n(দুই নাসারন্ধ্র বন্ধ)',
      'Close left nostril\nExhale through right':
          'বাম নাসারন্ধ্র বন্ধ করুন\nডান দিক দিয়ে শ্বাস ছাড়ুন',
      'Inhale through\nright nostril': 'ডান নাসারন্ধ্র দিয়ে\nশ্বাস নিন',
      'Hold breath': 'শ্বাস ধরে রাখুন',
      'Exhale through\nleft nostril': 'বাম নাসারন্ধ্র দিয়ে\nশ্বাস ছাড়ুন',
      'Close your right nostril and inhale through the left':
          'ডান নাসারন্ধ্র বন্ধ করুন এবং বাম দিক দিয়ে শ্বাস নিন',
      'Hold your breath': 'শ্বাস ধরে রাখুন',
      'Close your left nostril and exhale through the right':
          'বাম নাসারন্ধ্র বন্ধ করুন এবং ডান দিক দিয়ে শ্বাস ছাড়ুন',
      'Inhale through your right nostril': 'ডান নাসারন্ধ্র দিয়ে শ্বাস নিন',
      'Exhale through your left nostril': 'বাম নাসারন্ধ্র দিয়ে শ্বাস ছাড়ুন',
      'Exercise Complete!': 'অনুশীলন সম্পূর্ণ!',
      'Excellent! You have completed 10 rounds of alternate nostril breathing.':
          'চমৎকার! আপনি বিকল্প নাসিকা শ্বাসের ১০ রাউন্ড সম্পূর্ণ করেছেন।',
      'Great job! You\'ve completed 10 rounds of Alternate Nostril Breathing.':
          'খুব ভালো! আপনি বিকল্প নাসিকা শ্বাসের ১০ রাউন্ড সম্পূর্ণ করেছেন।',
    },
  };

  static const Map<AppLanguage, Map<String, List<String>>> _lists = {
    AppLanguage.english: {
      'breathingIntro': [
        'Welcome. I am here to guide you. Let us begin with the breath, the bridge between body and mind.',
        'Peace be with you. The breath is your anchor. Let us breathe together and find stillness.',
        'The mind is like clear water. Let us become still and begin.',
      ],
      'inhalePrompts': [
        'Breathe in. Draw life into every cell.',
        'Inhale. Feel the breath filling you.',
        'Breathe in deeply. You are receiving.',
      ],
      'holdPrompts': [
        'Hold. Rest in this moment of fullness.',
        'Be still. Stay soft and steady.',
        'Hold gently. Nothing needs to be forced.',
      ],
      'exhalePrompts': [
        'Release. Let go of what does not serve you.',
        'Exhale. Soften what you cannot control.',
        'Breathe out. Return to calm.',
      ],
      'poseTransitions': [
        'Now move into the next posture. Let the body follow the breath.',
        'Transition with awareness. Each movement is a meditation.',
        'Shift gently. Move with respect for the body.',
      ],
      'sessionCompleteLines': [
        'You have done well. Carry this stillness into your day.',
        'The practice is complete. The peace you found here stays within you.',
        'Well done. Return to the day with a steady heart.',
      ],
      'encouragement': [
        'The mind wanders. Gently return, without judgment.',
        'There is no failure in practice. Only returning again and again.',
        'You are exactly where you need to be.',
      ],
    },
    AppLanguage.hindi: {
      'breathingIntro': [
        'स्वागत है। मैं आपका मार्गदर्शन करने के लिए यहां हूं। आइए श्वास से शुरू करें, जो शरीर और मन के बीच सेतु है।',
        'आपके भीतर शांति रहे। श्वास आपका आधार है। आइए साथ श्वास लें और स्थिरता पाएं।',
        'मन साफ पानी जैसा है। आइए स्थिर होकर शुरू करें।',
      ],
      'inhalePrompts': [
        'श्वास लें। हर कोशिका में जीवन भरें।',
        'श्वास लें। श्वास को भीतर भरते हुए महसूस करें।',
        'गहरी श्वास लें। आप ऊर्जा ग्रहण कर रहे हैं।',
      ],
      'holdPrompts': [
        'रोकें। इस पूर्ण क्षण में विश्राम करें।',
        'स्थिर रहें। कोमल और संतुलित रहें।',
        'धीरे रोकें। किसी बात को जबरदस्ती न करें।',
      ],
      'exhalePrompts': [
        'छोड़ें। जो उपयोगी नहीं है उसे जाने दें।',
        'श्वास छोड़ें। जिसे नियंत्रित नहीं कर सकते, उसे नरम करें।',
        'बाहर छोड़ें। शांति में लौटें।',
      ],
      'poseTransitions': [
        'अब अगले आसन में जाएं। शरीर को श्वास के साथ चलने दें।',
        'सचेत होकर बदलें। हर गति ध्यान है।',
        'धीरे बदलें। शरीर के सम्मान के साथ चलें।',
      ],
      'sessionCompleteLines': [
        'आपने अच्छा किया। इस स्थिरता को अपने दिन में साथ रखें।',
        'अभ्यास पूरा हुआ। जो शांति आपने यहां पाई, वह आपके भीतर रहती है।',
        'बहुत अच्छा। स्थिर हृदय के साथ दिन में लौटें।',
      ],
      'encouragement': [
        'मन भटकता है। बिना निर्णय के धीरे लौट आएं।',
        'अभ्यास में असफलता नहीं होती। केवल बार-बार लौटना होता है।',
        'आप ठीक वहीं हैं जहां आपको होना चाहिए।',
      ],
    },
    AppLanguage.bengali: {
      'breathingIntro': [
        'স্বাগতম। আমি আপনাকে পথ দেখাতে এখানে আছি। আসুন শ্বাস দিয়ে শুরু করি, যা শরীর ও মনের সেতু।',
        'আপনার মধ্যে শান্তি থাকুক। শ্বাস আপনার ভরসা। আসুন একসঙ্গে শ্বাস নিই এবং স্থিরতা খুঁজি।',
        'মন স্বচ্ছ জলের মতো। আসুন স্থির হয়ে শুরু করি।',
      ],
      'inhalePrompts': [
        'শ্বাস নিন। প্রতিটি কোষে জীবন ভরুন।',
        'শ্বাস নিন। শ্বাস আপনাকে ভরিয়ে দিচ্ছে অনুভব করুন।',
        'গভীরভাবে শ্বাস নিন। আপনি শক্তি গ্রহণ করছেন।',
      ],
      'holdPrompts': [
        'ধরে রাখুন। এই পূর্ণ মুহূর্তে বিশ্রাম নিন।',
        'স্থির থাকুন। কোমল ও ভারসাম্যপূর্ণ থাকুন।',
        'নরমভাবে ধরে রাখুন। কিছু জোর করার দরকার নেই।',
      ],
      'exhalePrompts': [
        'ছেড়ে দিন। যা কাজে লাগে না তা যেতে দিন।',
        'শ্বাস ছাড়ুন। যা নিয়ন্ত্রণ করতে পারেন না তা নরম করুন।',
        'বাইরে ছাড়ুন। শান্তিতে ফিরে আসুন।',
      ],
      'poseTransitions': [
        'এখন পরের আসনে যান। শরীরকে শ্বাসের সঙ্গে চলতে দিন।',
        'সচেতনভাবে পরিবর্তন করুন। প্রতিটি গতি এক ধরনের ধ্যান।',
        'ধীরে বদলান। শরীরের প্রতি সম্মান রেখে চলুন।',
      ],
      'sessionCompleteLines': [
        'আপনি ভালো করেছেন। এই স্থিরতা আপনার দিনের সঙ্গে রাখুন।',
        'অনুশীলন সম্পূর্ণ। এখানে যে শান্তি পেলেন, তা আপনার ভেতরেই থাকে।',
        'খুব ভালো। স্থির হৃদয় নিয়ে দিনে ফিরে যান।',
      ],
      'encouragement': [
        'মন ঘুরে বেড়ায়। বিচার না করে ধীরে ফিরে আসুন।',
        'অনুশীলনে ব্যর্থতা নেই। আছে শুধু বারবার ফিরে আসা।',
        'আপনি ঠিক যেখানে থাকার দরকার, সেখানেই আছেন।',
      ],
    },
  };

  static const Map<AppLanguage, Map<String, String>> _poseInstructions = {
    AppLanguage.english: {
      'Mountain Pose':
          'Stand like a mountain: rooted, steady, and open to the sky.',
      'Warrior I': 'Be peaceful and strong. Ground your feet and reach upward.',
      'Tree Pose': 'Find your center. Let your roots hold you steady.',
      'Warrior I (other)':
          'Switch sides. Keep your breath steady and your body grounded.',
      "Child's Pose": 'Return to the earth. Rest here without striving.',
      'Downward Dog': 'Lengthen your spine. Let the body soften into the pose.',
      'Lotus Meditation': 'Sit in stillness. Let wisdom open like a lotus.',
    },
    AppLanguage.hindi: {
      'Mountain Pose':
          'पर्वत की तरह खड़े हों: जड़ से स्थिर, शांत और आकाश के लिए खुले।',
      'Warrior I': 'शांत और मजबूत बनें। पैर जमाएं और ऊपर उठें।',
      'Tree Pose': 'अपना केंद्र खोजें। अपनी जड़ों को आपको स्थिर रखने दें।',
      'Warrior I (other)':
          'दूसरी ओर जाएं। श्वास स्थिर रखें और शरीर को जमीन से जुड़ा रखें।',
      "Child's Pose": 'धरती की ओर लौटें। बिना प्रयास के यहां विश्राम करें।',
      'Downward Dog': 'रीढ़ लंबी करें। शरीर को आसन में नरम होने दें।',
      'Lotus Meditation': 'स्थिरता में बैठें। प्रज्ञा को कमल की तरह खुलने दें।',
    },
    AppLanguage.bengali: {
      'Mountain Pose':
          'পাহাড়ের মতো দাঁড়ান: শিকড়ে স্থির, শান্ত, আকাশের দিকে খোলা।',
      'Warrior I': 'শান্ত ও শক্তিশালী হোন। পা স্থির করুন এবং ওপরে উঠুন।',
      'Tree Pose': 'নিজের কেন্দ্র খুঁজুন। শিকড় আপনাকে স্থির রাখুক।',
      'Warrior I (other)':
          'দিক বদলান। শ্বাস স্থির রাখুন এবং শরীর মাটিতে স্থিত রাখুন।',
      "Child's Pose": 'মাটির দিকে ফিরে আসুন। চেষ্টা ছাড়া এখানে বিশ্রাম নিন।',
      'Downward Dog': 'মেরুদণ্ড লম্বা করুন। শরীরকে আসনে নরম হতে দিন।',
      'Lotus Meditation': 'স্থির হয়ে বসুন। প্রজ্ঞাকে পদ্মের মতো খুলতে দিন।',
    },
  };
}
